image: Visual Studio 2017

build_script: 
  - ps: .\build.ps1 -Target "Appveyor" -Configuration "Release"
  
# disable built-in tests.
test: off

artifacts:
- path: package\*.zip
- path: package\*.nupkg
